version: "3.9"

services:
  web:
    image: node:20-slim
    container_name: next_web
    working_dir: /app
    volumes:
      - ./app:/app            # maps local ./app folder to /app in container
    ports:
      - "3000:3000"           # Next.js dev server
    environment:
      - NODE_ENV=development
    command: >
      sh -c "if [ ! -f package.json ]; then
               npx create-next-app@latest . --use-npm --yes;
             fi &&
             npm install &&
             npm run dev"
